### ISSUE TITLE
content negotiation oddity

### ISSUE THREAD

**Issue by jkunze** [jkunze/n2t-eggnog#2]
Here's an example of the passthrough content negotiation: This resolves as expected:
`curl -v "https://n2t.net/igsn:PRR047915"`
Whereas this does not:
`curl -v -H "Accept: application/json" "https://n2t.net/igsn:PRR047915"`
The latter responds with:
` # inflections under construction`
` # reference https://n2t.net/e/n2t_apidoc.html`

**Comment by datadavev** [comment]
This issue particularly relevant to programmatic clients using the N2T service to resolve identifiers where multiple serializations of the content may be available on the resource server (i.e. the server where the identified content is available). Using the aforementioned identifier `igsn:PRR047915`, the resolution steps when using no `Accept` header are:

```
https://n2t.net/igsn:PRR047915 
1. -> 302 https://hdl.handle.net/10273/PRR047915 
2. -> 302 https://data.geosamples.org/sample/igsn/PRR047915 
3. -> 301 https://app.geosamples.org/sample/igsn/PRR047915 
4. -> 200 Content-Type: text/html, <<Response Body>>
```
With `<<Response Body>>` being the default HTML response offered by the resource server.

When requesting a content type of `application/json`, the response is:

```
https://n2t.net/igsn:PRR047915 
1. > 200 text/plain; charset=UTF-8, <<Response Body>>
```
With `<<Response Body>>` being the message:
```
# inflections under construction
# reference https://n2t.net/e/n2t_apidoc.html
```

When requesting a content type of `application/json` from the `hdl.handle.net` server in the first sequence above, the resolution steps are:
```
https://hdl.handle.net/10273/PRR047915 
1. -> 302 https://data.geosamples.org/sample/igsn/PRR047915 
2. -> 301 https://app.geosamples.org/sample/igsn/PRR047915
3. -> 302 https://app.geosamples.org/webservices/display.php?igsn=PRR047915
4. -> 200  Content-Type: text/json; <<Response Body>>
```
With the final response body being the expected JSON-LD.

The N2T service *should* simply ignore the `Accept` request header and provide the registered redirection URL in the `Location` response header, similar to the `hdl.handle.net` response.

If N2T can provide additional metadata about the identifier, then it could do so using `Link` headers [[rfc8288](https://tools.ietf.org/html/rfc8288)]. This would enable redirection to work as expected while still advertising the availability of additional information, if necessary or applicable.

**Comment by jkunze** [comment]
I think this content negotiation bug has been fixed in n2t-dev.n2t.net. Please give it a try and confirm.

The last paragraph of the comment contains a good suggestion, which I'll turn into a second issue.

**Comment by datadavev** [comment]
Looks good on the dev server.

**Comment by jkunze** [comment]
This specific fix went into n2t prd this morning. Please let me know if you see notice any problem.
